
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-gke-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-gke-app
  template:
    metadata:
      labels:
        app: node-gke-app
    spec:
      containers:
      - name: node-gke-app
        image: us-central1-docker.pkg.dev/data-fabric-423913-r0/node-gke-repo/node-gke-app:latest
        ports:
        - containerPort: 8080
